sudo: false
language: node_js
node_js:
  - 12
os:
  - linux
before_install:
  - npm i -g npm@6.9.0 codecov
  - npm --version
install:
  - npm ci
script:
  - npm run lint && jest --coverage
  - codecov
